# Generated by Django 2.0.2 on 2018-02-25 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180223_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=('default_slug', django.utils.timezone.now), max_length=100),
            preserve_default=False,
        ),
    ]
