# Generated by Django 2.0.2 on 2018-02-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(default='Nonee', on_delete=django.db.models.deletion.CASCADE, to='blog.Categorie'),
        ),
    ]
