# Generated by Django 2.0.2 on 2018-02-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_article_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
