# Generated by Django 2.0.2 on 2018-02-27 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duree_Loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Enregistrement_Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('commentaire', models.TextField(null=True)),
                ('date_loc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de location')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duree_loc', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruban_vert.Duree_Loc')),
            ],
            options={
                'verbose_name': 'Enregistrement',
                'ordering': ['date_loc'],
            },
        ),
        migrations.CreateModel(
            name='Registre_Tarif_Loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duree_loc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ruban_vert.Duree_Loc')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bateau', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='registre_tarif_loc',
            name='type_loc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ruban_vert.Type_Loc'),
        ),
        migrations.AddField(
            model_name='enregistrement_caisse',
            name='tarif',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruban_vert.Registre_Tarif_Loc'),
        ),
        migrations.AddField(
            model_name='enregistrement_caisse',
            name='type_loc',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruban_vert.Type_Loc'),
        ),
    ]
