# Generated by Django 2.0.2 on 2018-03-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruban_vert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement_caisse',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enregistrement_caisse',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
