# Generated by Django 2.0.2 on 2018-03-06 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL_longue', models.URLField(unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('createur', models.CharField(max_length=40, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
